services:
  db:
    image: postgres
    container_name: db
    restart: always
    env_file:
      - tallow-book-back/.env
    ports:
      - 5433:5432
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  node:
    container_name: node
    build: .
    ports:
      - 1234:5000
    env_file:
      - tallow-book-back/.env
    depends_on:
      - db

  react:
    container_name: react
    build: ./tallow-book-front
    volumes:
      - react-volume:/var/www/html

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - 8080:80
    volumes:
      - react-volume:/var/www/html
    depends_on:
      - db
      - node
      - react

volumes:
  postgres-volume:
  react-volume: