services:
  db:
    image: postgres
    container_name: db
    env_file:
      - tallow-book-back/.env.test
    ports:
      - 5433:5432

  node:
    container_name: node
    build: ./tallow-book-back
    ports:
      - 5000:5000
    env_file:
      - tallow-book-back/.env.test
    depends_on:
      - db